### ISSUE TITLE
[bug] Cannot update report fields error

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#107]
We recently started seeing the attached error somewhat randomly whenever we try to look at a dashboard in an uneditable mode via the shared link functionality. Sometimes it will pop up as soon as you load up the dashboard, but other times it doesn't pop until you've navigated around a bit. Not sure what could be causing it, but presumably something to do with link sharing/non-editing mode view?

![image](https://user-images.githubusercontent.com/11720378/157266028-87fb2406-0cee-4585-834b-f29c38a8b2a1.png)

**Comment by emigre459** [comment]
Note that I was using Chrome 99.0.4844.51 in Windows 10 and Neodash 2.0.12 (via the graphapp.io link)

**Comment by nielsdejong** [comment]
Hi @emigre459 , this issue is resolved as of the latest update (2.0.13). Thanks for the pointer!
