### ISSUE TITLE
Wrong docker run in README.md

### ISSUE THREAD

**Issue by paltusplintus** [nielsdejong/neodash#113]
In the "Run locally with Docker" section the recommended docker run statement is incorrect:
`docker run -it --rm -p 8080:80 nielsdejong/neodash`
should be
`docker run -it --rm -p 5005:5005 nielsdejong/neodash`

**Comment by nielsdejong** [comment]
hi @paltusplintus , thanks for catching this! Have corrected the port number in the master branch README.
Best,
Niels
