### ISSUE TITLE
[Feature Request] Advanced settings documentation

### ISSUE THREAD

**Issue by Cobra5197** [nielsdejong/neodash#117]
Could you add in your in-app documentation, the advanced settings documentation for each report type?

For example, in the table report, I was not sure how to use the `Relative Column Sizes`.

Thank you!
Cobra

**Comment by nielsdejong** [comment]
hi @Cobra5197 ,

Thanks for reminding us of this one. We've now got documentation available for this on the project wiki:
https://github.com/nielsdejong/neodash/wiki/Reports

Hope that is what you needed,
Niels

**Comment by Cobra5197** [comment]
Hi @nielsdejong,

Yeah, it's perfect!

Thank you,
Cobra
