### ISSUE TITLE
BUG: Map does not show up in exported image

### ISSUE THREAD

**Issue by dschmitz89** [nielsdejong/neodash#129]
The new image download functionality does not contain the leaflet map.
Rendered Example in Dashboard:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/40656107/166868387-eb914424-89ec-41e9-9b22-2693f0a64946.png">

Exported PNG:
![image (8)](https://user-images.githubusercontent.com/40656107/166868496-b9131536-2d45-4cf5-a956-302bf309b934.png)

One side note about the PNG exports: would it be possible to increase the resolution to sth like 300dpi or have a global setting for this?

**Comment by nielsdejong** [comment]
Hi @dschmitz89 ,
Have resolved this by changing the library that generates the images. This'll be present in the 2.1 release later this week.

Thanks,
Niels

**Comment by BennuFire** [comment]
Closed on 35291192802ada6cf75d433113632ad1a42cd573  Version 2.1.1
