### ISSUE TITLE
Recommend making standalone web-based variant

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#29]
This tool is extremely helpful for us when we're prototyping out a visualization set for a new client. However, due to some restraints on client systems, we can't always install Neo4j Desktop and instead clients just access the remote graph server we've setup via their web browser. If we could set up NeoDash to run on a pre-specified port in a similar fashion, that would be amazing!

**Comment by nielsdejong** [comment]
Hi Emigre,

Thanks for reaching out! Great to hear that the tool is helping you at your client.
I don't yet provide a prebuilt instance of NeoDash, but it is currently possible to build NeoDash as a standalone web application yourself using npm. After cloning the repository, run this in the main folder:
```
npm i
npm run-script build
```
That should create a `dist` folder that you can host on a client system.

Perhaps it is relevant to say that I'm currently rebuilding NeoDash (from scratch) for the 2.0 release. From this version onwards, I aim to make this process easier by providing a standalone web-version. Expect this to be released somewhere in November, will keep you posted.

Niels

**Comment by emigre459** [comment]
Very cool, thanks!
