### ISSUE TITLE
Glitch in hosted demo

### ISSUE THREAD

**Issue by JipSogeti** [nielsdejong/neodash#36]
Hi Niels,

So far I really enjoy playing around with Neodash! My local installation works fine (latest dev branch). But the version hosted at [neodash.graphapp.io](http://neodash.graphapp.io/) seems to have a glitch with the sidebar. It won't collapse and is always on top of the dashboard. Perhaps it needs to be redeployed with the latest version?

<img width="679" alt="Schermafbeelding 2021-11-30 om 14 29 59" src="https://user-images.githubusercontent.com/94383160/144056142-11c904c5-cff0-4c38-ae16-e28a2faadd88.png">

I'd love to show Neodash to some of my colleagues and sending them a link to neodash.graphapp.io would definitely be the easiest way to do so :)

**Comment by nielsdejong** [comment]
Hi Jip,

Interesting, haven't seen that on my side before. Looks like you're using Microsoft Edge from the screenshot above. Likely there's an issue there. For the short term, could you see if you get the same issue with Chrome/Firefox on your side?

I'll try Edge myself on my old windows laptop and see if I can fix the css bug locally.

Best,
Niels

**Comment by JipSogeti** [comment]
Interesting indeed. It's Microsoft Edge Versie 96.0.1054.34 (Officiële build) (x86_64) on MacOS 11.6.1 (20G224). No need to get out your old Windows laptop haha. Since the browser is Chromium based I'm surprised to see that indeed this doesn't happen in Google Chrome (just confirmed).

When serving neodash with `npm run dev` from the latest dev branch, the glitch doesn't occur in Edge... So I don't know what there is to fix...

**Comment by nielsdejong** [comment]
Just tried on my windows laptop, seems to be working there too.
Very strange. Could you do a CTRL+SHIFT+R (hard cache reset) in the browser just in case?
Sometimes the browser does some aggressive caching of the previously build bundles. 

Does the browser console show any errors btw?

**Comment by JipSogeti** [comment]
Nice! It was just a cache issue 😄 Thanks for the help!
