### ISSUE TITLE
Parameter select in dashboard builder is not displaying the correct list of a node's properties after update

### ISSUE THREAD

**Issue by lighteternal** [nielsdejong/neodash#39]
Hi and thanks for this great tool. 

After the recent update to v2, I noticed a number of bugs in existing dashboards (also present in the newly created ones). I created a brief list with screenshots. All of the following were working in the previous version: 

**1. Adding a Parameter Select box: The Property Name dropdown menu is not updated based on the selection of the Node Label.** That leads to not being able to select node-specific properties.   
![Image Pasted at 2021-12-7 10-56](https://user-images.githubusercontent.com/22905968/145016577-8577a68c-1510-4334-9951-941bdb487e34.png)

2. **Similar to 1. the available resources for visualization are not updated in the dropdown menu**. 
![Image Pasted at 2021-12-7 10-58](https://user-images.githubusercontent.com/22905968/145016930-cc7fecdb-c5ba-4e8b-ae0d-8ec4ff6b544a.png)

3. **Nodes with multiple labels (e.g. a node is of  label "Resource" and "nS0_EC-Project") cannot be differentiated and color-coded**.
![Image Pasted at 2021-12-7 12-21](https://user-images.githubusercontent.com/22905968/145017184-da8e6a2f-9da9-4829-b6fa-2462c13bce74.png)

It's possible that **having multiple labels for each node** is the source for this confusion, although it's still unclear to me as to why, given that it worked perfectly in the previous version. 

I am using Neodash: v2.0.2 and Neo4j Desktop: v1.4.10.

**Comment by nielsdejong** [comment]
Hi Dimitris,
Thanks for reaching out and reporting these issues.

I will do some experimenting on my site to see if I can reproduce the problems locally. I take it you have a database with nodes that can have multiple labels, where each label has a different set of distinct properties?

It is very much possible that these issues weren't present in the previous version of the app. I have  rebuilt the tool completely from scratch for v2 to have better state management + be more performant. It could perhaps be that some features were not migrated successfully. If you find any other inconsistencies in the meantime, please let me know, happy to hear your findings.

Best,
Niels

**Comment by lighteternal** [comment]
> I will do some experimenting on my side to see if I can reproduce the problems locally. I take it you have a database with nodes that can have multiple labels, where each label has a different set of distinct properties?

Thanks for the quick response!

Yes, this is exactly the case. Some of the properties are universal for all nodes, but most of them are distinct for each type of node. 
With regard to the labels, all nodes share the same label ("Resource"), while also having more informative ones (e.g. "Organisation", "Project" etc.). Given that the database is provided and updated periodically by external source, I am not allowed to modify its structure (i.e. remove the double label).

**Comment by nielsdejong** [comment]
Hi Dimitris,
I have pushed a fix today (v2.0.3) that addresses the issues.
Could you check whether the issues are resolved from your side?

**Comment by lighteternal** [comment]
Hi Niels, 

I am glad to report that all the aforementioned issues are solved! 
Many thanks again for your quick response and kudos for developing this very useful reporting tool for Neo4j. 
Clossing the issue. 

Dimitris
