### ISSUE TITLE
Using datetime values for x-axis linecharts

### ISSUE THREAD

**Issue by sushivi** [nielsdejong/neodash#40]
Hi Niels, 

First of all, I like your dashboarding tool a lot, keep up the good work!

I'm currently working with a graph database that includes timestamps. It would be nice if it is possible to not only use numeric values for the x-axis, but also datetime-like values.

**Comment by nielsdejong** [comment]
Hi Vi,
Thanks for the suggestion! I'll look into that one, based on a first glance, I expect it to be possible with the visualization library.
If you're looking for an intermediate solution, you can (for now), also cast the result dates to numbers in your cypher query:

Example:
```
RETURN datetime('2015-06-24T12:50:35.556+0100').week as weeknumber
```

This will probably not look as nice, but will perhaps accomplish what you're looking for.

Will keep you posted on the progress.

Best,
Niels
