### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by ryansun96** [nielsdejong/neodash#42]
The project is awesome and so is the online demo. It would be great if we can build docker images automatically and publish it to a registry so users can deploy more easily.

**Comment by nielsdejong** [comment]
Hi Ryan,
Thanks for your suggestion, nice idea! I'll put this on my roadmap for early 2022. Will post updates on this issue as I make progress.

Niels

**Comment by nielsdejong** [comment]
Hi, this issue was resolved in PRs #63 and #64.
there's an experimental docker image also published on Docker Hub:
https://hub.docker.com/r/nielsdejong/neodash

hope this works,
Niels
