### ISSUE TITLE
Chosen graph labels not applied

### ISSUE THREAD

**Issue by JipSogeti** [nielsdejong/neodash#45]
Hi Niels,

When I export my dasyboard to JSON, I can see that the label selection is saved:
```json
{
  "title": "Which entities are involved?",
  "query": "MATCH (c1:Country)--(:Entity)<-[:ORIGINATOR]-(f:Filing)-[:BENEFITS]->(:Entity)--(c2:Country)\nWHERE c1.name =  \"Netherlands\"\nAND distance(c2.location, point({latitude: 53, longitude: 9})) < 3000000\nWITH c1, c2, sum(f.amount) as amount\nWITH c1, c2, apoc.create.vRelationship(c1, \"TRANSFER\", {amount: amount}, c2) as t\n\nMATCH path=(c2:Country)-[r]-(e:Entity)\nRETURN c1, t, c2, collect(path)[0..10]",
  "width": "6",
  "type": "graph",
  "height": "3",
  "selection": {
    "Country": "location",
    "Entity": "id"
  },
  "settings": {}
}
```

In this case I selected to show `location` and `id` on the nodes.

But when I import the JSON file again, the selected labels aren't applied. It defaults back to show `name` and `name`.

<img width="310" alt="Schermafbeelding 2021-12-16 om 11 58 52" src="https://user-images.githubusercontent.com/94383160/146360122-c828844f-4bc4-400d-a5d0-3ea550e29de6.png">

Would be great if this selection could be re-applied on import :)

**Comment by nielsdejong** [comment]
Good catch, will fix this one sometime next week.
Niels

**Comment by nielsdejong** [comment]
Fixed in https://github.com/nielsdejong/neodash/commit/523931bfe91f68618bd61d5116e5512e87804e2a
(Both for graphs & line charts)
