### ISSUE TITLE
Show nodes on map related to location

### ISSUE THREAD

**Issue by JipSogeti** [nielsdejong/neodash#46]
Just wanted to leave this here for others who may struggle with showing nodes on the map.

I have nodes without latitude/longitude attributes, but they are related to a Location node which has them.
In order to put those nodes on the map, in the right location, I had to use this Cypher query:

```
MATCH (n)-[]-(l:Location)
WITH collect(n{.*, id: id(n), label: labels(n), latitude: l.latitude, longitude: l.longitude}) as items
return items
```

Basically this keeps all the attributes of node `n` and temporarily adds lat/long attributes (only for plotting, not modifying in the database). The trick was to also add the `id` and `label`, without them the map wouldn't plot the returned data.

Perhaps it would be an idea to document what format the map chart expects.

**Comment by nielsdejong** [comment]
Nice find! this is somewhat of a 'hidden feature' that I never properly documented:
https://github.com/nielsdejong/neodash/blob/ad2b5a2a3fab9c660fc43704b2c6126324832459/src/chart/MapChart.tsx#L66

I'll add an extra example query to the Documentation model that demonstrates how to do this. 
I can see how that is helpful when you want to customize the nodes displayed on the map.

P.S. - for reference: you could accomplish something similar (if you have apoc installed) by using virtual nodes/relationships:
https://neo4j.com/labs/apoc/4.1/virtual/
I use these quite often and find it helpful for doing some one-off visualizations without adjusting the database.

**Comment by nielsdejong** [comment]
Resolved in:
https://github.com/nielsdejong/neodash/commit/59deec386de20db44d66b1fd419f45f07691cf35

**Comment by JipSogeti** [comment]
Awesome 😄
