### ISSUE TITLE
`Parameter Select` to use Cypher query output

### ISSUE THREAD

**Issue by chihpoc** [nielsdejong/neodash#48]
Is it feasible to allow `Parameter Select` to use the Cypher query output? Thanks!

**Comment by nielsdejong** [comment]
Hi Chihpo,

Thanks for the suggestion. Do you mean to let people select cypher parameters based on output in other reports?

E.g. something like this:
> If I render my data as a table, clicking on a cell with set a global parameter with that value.

**Comment by JipSogeti** [comment]
> > If I render my data as a table, clicking on a cell with set a global parameter with that value.

I'm not sure if that's what @chihpoc means. But I would find it really useful if one could set a global parameter by clicking a cell in the table, as an alternative to the Parameter Select chart.

**Comment by nielsdejong** [comment]
Going to close this one as I'm cleaning up the issue log.
This topic will be picked up here: https://github.com/nielsdejong/neodash/issues/27
