### ISSUE TITLE
[Feature Request] Free Text Parameter / [Help] Using Parameter Select as Free Text  

### ISSUE THREAD

**Issue by nukerxy** [nielsdejong/neodash#55]
Hello.

I love NeoDash so far, it makes prototyping quick and easy.

I want implement a search on nodes that meet a certain condition, something like

```
match(x [....])
where x.$neodash_x_property CONTAINS $neodash_searchword
return x limit 1000
```
where `$neodash_x_property` is selected by a parameter select
and `$neodash_searchword` is selected using a free text field.

Am I missing some advanced option to use the current parameter select as a free text input?
Are there any design choices or technical hurdles opposing such an implementation?

I do know that searching on properties is inefficient.
My data set is small. << 1M nodes
The search will be rarely used. I cannot remodel the graph. (It wouldn't make sense aswell, since this feature will rarely be used)

Thanks for considering this change!

**Comment by nielsdejong** [comment]
Hi, I fixed this in https://github.com/nielsdejong/neodash/commit/d3ca8767bc3a514206ae5cc8da7ac831000ef52a
This'll be part of the 2.0.6 release which I'll publish sometime next week.

Cheers,
Niels
