### ISSUE TITLE
How to adjust the maximum query time interactively?

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#58]
I'm finding that I need to extend my query response time beyond the default 20 seconds, due to the size of my graph (I'm only able to get it to execute within 75 seconds after implementing relevant indexes). Is there any way to adjust the max query response time configuration without needing to build and deploy the project yourself (e.g. via the interface provided on http://neodash.graphapp.io/)?

**Comment by cagataytulu** [comment]
Hi emigre459, i was also trying to find a way to maximize query time in the neodash, as a workaround I have used apoc procedure apoc.cypher.runTimeboxed and it worked, you can try it.
![image](https://user-images.githubusercontent.com/10770873/148902561-a82c74fb-0af3-438a-af1b-8ab64c6cf214.png)

**Comment by nielsdejong** [comment]
Hi @emigre459, thanks for the suggestion. I'll work in a feature in 2.0.6 to make this timeout configurable:
https://github.com/nielsdejong/neodash/blob/master/src/config/ReportConfig.tsx#L28

**Comment by nielsdejong** [comment]
Fixed this (among some other small things) in here:
https://github.com/nielsdejong/neodash/commit/a2fe46b8e7d2a1c1a7d31be74bc0dceafec1bec9
