### ISSUE TITLE
Feature Request (Single Number Tile)

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#59]
A few different thoughts as I'm using the Single Number Tile on ways to improve it:

1. Allow for more automated vertical text alignment, akin to the left/center/right dropdown used for horizontal alignment in the Text Align advanced setting instead of having to adjust the margin padding in pixels. This is especially important when working with two single value tiles side-by-side that have different font sizes, as a larger font size would require a different padding number to align it well with a smaller font size tile that is also padded (see attached screenshot for an example of what happens when you try to use the same padding value for both).
2. Generally for all tiles: allow for some preset colors that can be entered as free text, not just as the RGBA code. So allow for RBGA codes still, as this is great flexibility, but build in some basic choices too (e.g. from a dropdown maybe or a color picker if possible)
3. Modify the default font size to at least 64, if not 128, as even small laptop screens can usually handle those values and they should also accommodate reasonably large numbers (e.g. my screen could handle a font of 64 with numbers in the hundreds of millions).
4. Recommend adding the ability to include a thousands separator (e.g. ",") as large numbers become hard to view. Also would ideally include an option to turn scientific notation on/off (e.g. 1.57E8).
5. Dynamic font sizing would be great as well, to make sure that the font size chosen doesn't cut off a large number's digits (especially since users may not be aware this is happening and draw false conclusions as a result). 

![image](https://user-images.githubusercontent.com/11720378/148785111-51faf42f-a194-4f50-abbd-b3d18e1a529a.png)

**Comment by nielsdejong** [comment]
Hi @emigre459 ,
Good points, going through them one-by-one:
1. Agree, having a `vertical-align` property is probably a lot easier to use than a margin.
2. I'll see if I can get a color picker in like this one: https://www.npmjs.com/package/material-ui-color-picker - that should be the best of both worlds.
3. Not super sure about this one. Problem is that the single value reports could also display string values, datetimes, and other things. I'd rather be conservative here and pick a small value to avoid the value clipping you mentioned.
4. I like this a lot. Perhaps this can be a global setting for an entire dashboard called 'Number format' or something similar.
5. I think this'd be ideal, but possibly tricky to implement. I remember trying this in the original NeoDash and it was pretty fiddly. 

Will post progress on the implementation here as I get there.

**Comment by nielsdejong** [comment]
Hi @emigre459 ,
Part of your suggestions are addressed in the latest release (2.0.10):
- The default font-size for single values was changed to 64.
- Numbers are now formatted based on the locale settings of the browser.

I'll leave this issue open to address the other points in a later release.

**Comment by nielsdejong** [comment]
Status update: of 2.0.13, the margin-based vertical positioning of single values has been changed to a vertical-align property.

**Comment by nielsdejong** [comment]
HI @emigre459 , I'm going to close this issue to clean up the backlog a little.
I think we've addressed most of the issues. A color picker is also present now in the rule-based styling, so that'll soon be added to the other color field as well.

Thanks for the suggestions as usual,
Niels
