### ISSUE TITLE
[Feature Request] Graph Tile Popup Enhancement

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#61]
The graph tile type is quite good, thank you!

As you can see in the screenshots below, if you have a long-value property in a node, when you click on the node to see its pop-up pane in fullness, the text is all right-justified. As this makes it look like all other properties are null/blank (until you scroll all the way to the right), it would probably be more helpful if the property value text were left-justified.

![image](https://user-images.githubusercontent.com/11720378/149001746-c365435a-9cab-4d2a-8d0f-c2c98134fc34.png)
![image](https://user-images.githubusercontent.com/11720378/149001823-ef406321-1214-4c34-afea-028055827ba6.png)

**Comment by nielsdejong** [comment]
Good call, I fixed this to left-aligned in the latest commit on the `develop` branch.
