### ISSUE TITLE
Standalone, non editable deployment

### ISSUE THREAD

**Issue by dschmitz89** [nielsdejong/neodash#66]
Hi,

thanks for the latest version 2.0.6 :)

We would be interested in a standalone deployment of a dashboard without any editing capabilities anymore to avoid people misuing the DB. When we deploy testwise as "standalone", the menu and the possibility to make the app editable is still there. Maybe we are using the app wrongly too. Could you maybe provide a small description also in the docs how this would be possible?

**Comment by nielsdejong** [comment]
Hi @dschmitz89 ,

This is a great idea, but you're right, it's currently not possible to create a "standalone" deployment.
Coincidentally I'm planning to implement this soon as I had one of Neo4j's customers request the same thing.

My feel is to create two "deployment modes":
- Editor mode (basically the app as-is).
- Standalone mode. (Auto-connects to a hardcoded Neo4j database, automatically loads a dashboard with all editing options disabled).

Would that be aligned with your use-case? Let me know if you have any thoughts on this.

P.S. once you're at the point of a standalone deployment, it would be great if you could share your story with us! (If you are allowed to of course)  I'm currently looking to collect some stories (blog posts etc.) from people using NeoDash to share with others.  Given that you're already planning to deploy it in a standalone-setting, I'm assuming you're already pretty far ahead in the dashboarding process. Personally very interested to see how people use the tool too. Let me know if you'd be up for this, happy to have a chat.

**Comment by dschmitz89** [comment]
Hi @nielsdejong ,

awesome, that standalone mode sounds exactly like what we would need!

Would love to have a chat about our dashboard ideas. Will talk to my project partners and our neo4j contacts.

**Comment by nielsdejong** [comment]
Perfect, will post updates on the standalone feature as I get there.
Would be great to have a chat about your project sometime. Could you send me an e-mail at niels.dejong@neo4j.com? We can set something up.

Thanks,
Niels

**Comment by Good4m** [comment]
Hi everyone, I have a **huge** need to publish a static version of the dashboard as well. I just need to publish a report once a day showing a static representation of the dashboard for managers. I don't need filtering or anything to be available. Also, I'm loving the product. It's great! Thank you for all your hard work.

**Comment by nielsdejong** [comment]
Hi @dschmitz89 & @Good4m ,
The latest version now support running the app in a standalone mode.
There's some info in the README on how to set this up. Let me know if you can get this working!

Niels

**Comment by nielsdejong** [comment]
Closing this one to clean up, please reach out if there's any issues/questions.

**Comment by dschmitz89** [comment]
You were too fast for us. Works like a charm now, thank you!
