### ISSUE TITLE
Line Chart: Weird errors

### ISSUE THREAD

**Issue by JoridK** [nielsdejong/neodash#70]
Hi again,

one larger bug that confused me a lot (and still does) happens when I try to create a Line Chart. 
I can get the data into a nice table without problems:
![Table](https://user-images.githubusercontent.com/99267906/153007487-f75e3606-2d5a-44f9-898d-27555bdef50a.png)
But then, when I switch to a Line Chart, I get this message:
![Error Message](https://user-images.githubusercontent.com/99267906/153007582-cc679e38-f195-4bd1-89ba-b48b420d47a6.png)
If I save the dashboard as a json, close the browser (Chrome / Edge), and import the saved dashboard, at least I can select the axis:
![Parts of a chart](https://user-images.githubusercontent.com/99267906/153007911-aa4898c5-840f-4342-9b96-fe8214b78962.png)
Now, for the y-axis, at first it only gives me "xhour" as an option. If I click that, the option suddenly disappears and I get the correct options for the chart. I can then finally display the chart.

**Comment by nielsdejong** [comment]
hi @JoridK ,
All line chart issues should be resolved in the latest release I published today (2.0.10). 
Please get in touch if you run into any more issues!

**Comment by JoridK** [comment]
Works well now indeed, thanks!
