### ISSUE TITLE
Trouble with Line Charts

### ISSUE THREAD

**Issue by Good4m** [nielsdejong/neodash#77]
**Issue:**
Bar chart is working as expected with the query below but **Line chart** gives an error.

**Query:**
MATCH (n:Event)
RETURN 
  apoc.date.format(TIMESTAMP(n.createdAt), 'ms', 'MM-dd') AS Day,
  COUNT(n) AS Count
ORDER BY Day ASC
LIMIT 30

**Error:**
Data was returned, but it can't be visualized.
This could have the following causes:
- a numeric value field was selected, but no numeric values were returned. 
- a numeric value field was selected, but only zero's were returned.
- Your visualization expects nodes/relationships, but none were returned.

---

Here is the same query working fine as a Bar chart:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1824966/153925055-4668c0ab-1618-4041-8e7e-ab7704dcdbcf.png">

Is there something I am doing wrong? I'd expect the bar and line charts to behave the same.

Thanks!

**Comment by nielsdejong** [comment]
Hi @Good4m ,
The line chart currently only supports plotting Neo4j datetime values on the x-axis.
You'll have to cast to datetime like this:
```
UNWIND [["2022-2-5",2],["2022-2-6",4]] as data
RETURN datetime(data[0]) as x, data[1] as y
```
Let me know if this works.

Best,
Niels
