### ISSUE TITLE
Parameter Select: custom/auto-resizing of text box

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#78]
For free text Parameter Select tile type (although probably relevant for other types of PS tiles too), I'm not seeing the text box expand with input/have the ability to be expanded regardless of tile size. I have a use case in which users will be inputting a list of strings that are then used for filtering elsewhere, so they may  need a fair amount of space in the text box to enter all their words of  interest. Is there a way to do this? If not, could this be added to the feature wishlist please? 

![image](https://user-images.githubusercontent.com/11720378/153927380-a598547c-7d68-4575-8900-994fd133f135.png)

**Comment by nielsdejong** [comment]
Hi @emigre459 ,
This is currently not possible, but it makes sense to autosize the textbox to the width of the report, agree.
Will add this as a feature in the next release.

Thanks for the suggestion!

**Comment by nielsdejong** [comment]
This feature was added as part of the 2.1 release, thanks for your suggestion!
Niels
