### ISSUE TITLE
Graph: Relationship Color vs Relationship Width

### ISSUE THREAD

**Issue by JoridK** [nielsdejong/neodash#79]
Hi,

I have one graph where I would like to colour the relationships and modify their width with variables.
If I only do one of the two, it works fine. 
If I add a variable for "Relationship Color Property" and another for "Relationship Width Property", the width property seems to be ignored.
Here is the graph without the colour variable: 
![without colour](https://user-images.githubusercontent.com/99267906/154058215-ba7e51df-277d-4955-9597-ce3e1e6bcb76.png)
And here with the colour (no other changes made):
![with colour](https://user-images.githubusercontent.com/99267906/154058254-8a5d5533-98a4-4501-a6cc-455580bd2a3a.png)

**Comment by nielsdejong** [comment]
Hi @JoridK ,

Just tried this out locally on a virtual graph:
```
WITH
    apoc.create.vNode(["Person"], {name:"bob"}) as a,
    apoc.create.vNode(["Person"], {name:"alice"}) as b
RETURN a,b,apoc.create.vRelationship(a,"LIKES",{amount: 10, class: "blue"},b)
```
Then with the following settings:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/1754968/154219737-2a77eb55-4024-4ad5-8627-49a666bea916.png">
<img width="812" alt="image" src="https://user-images.githubusercontent.com/1754968/154219797-5b6a5dd7-8865-4de3-a3ee-2996fd94b635.png">

It seems to work for me, perhaps it has something to do with the data in Neo4j? Could you share your query and the data in the database?

**Comment by JoridK** [comment]
It works for me now as well, I think I configured the variable for the width wrongly. It was at 0 for that connection, even though it should not have been. What is a bit odd is that it was larger when there was no color (width was still at zero...) but I cannot replicate that either. So I think this issue is obsolete unless I run into it again. Thanks for looking into it :)

**Comment by nielsdejong** [comment]
Hi @JoridK , great! just cleaning up the backlog so closing this issue. 

Have a good week,
Niels
