### ISSUE TITLE
Sorting Dropdowns 

### ISSUE THREAD

**Issue by JoridK** [nielsdejong/neodash#81]
Hi again,

as you can see, I am busy building dashboards.....

I have a couple of dropdown menus for graphs etc where there are a lot of entries (let's say fifty or so). I am not sure what criteria they are currently being ordered by, but for human users it would be really nice if they could be sorted alphabetically, with "(no label)" either on top or at the bottom.

**Comment by nielsdejong** [comment]
Hi Jorid,

Currently there is no ordering on dropdowns but I agree that sorting alphabetically makes a lot of sense.
I'll add this to the list of features to put into the next release.

Thank you,
Niels

**Comment by nielsdejong** [comment]
Hi @JoridK - as of 2.0.13 the properties in dropdowns are now sorted alphabetically.
Thanks again for the suggestion!
