### ISSUE TITLE
[Feature Request] Tab Re-ordering

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#83]
Right now, it appears we can only create new report tabs (automatically placed at the end of the other tabs) and delete them, but not simply change their ordering. Perhaps there could be a drag-and-drop functionality for this (most intuitive)?

**Comment by nielsdejong** [comment]
I like this one. I've been meaning to also somehow change the tabs turn into a horizontal scrollbar instead of a (strange) vertical scroll that appears when you have too many pages. Will put these together as one issue.

**Comment by BennuFire** [comment]
Closed on 35291192802ada6cf75d433113632ad1a42cd573 
Version 2.1.1

Enjoy!
