### ISSUE TITLE
[Feature Request] Sort Graph tile properties alphabetically

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#86]
Right now, if you have many properties on a node and want to inspect them more closely, the tooltip popup is great (e.g. clicking on a node anchors its popup in the center of the tile, allowing you to inspect it closely, copy values, etc.). Thank you! However, with a large enough set of properties, it can be hard to find what you're looking for quickly. One thing I've noticed Neo4j Browser does in this case is alphabetizing the properties by their keys. This is intuitive and definitely speeds up the property inspection process.

**Comment by nielsdejong** [comment]
Great idea, will add this into the next release (2.0.12)!

**Comment by nielsdejong** [comment]
Hi @emigre459 - this one has also made it into 2.0.13 and should be working.
Best,
Niels
