### ISSUE TITLE
Hardcode username and password for standalone deployment

### ISSUE THREAD

**Issue by dschmitz89** [nielsdejong/neodash#88]
Hi again,

thanks for the standalone capabilities!

I think there are many cases in which a dashboard is basically read-only for a very large audience. In that case, it would be very useful to hardcode a user and password into the config file for standalone deployment. Would you consider such a use case in future? Not necessary bestest of practice everywhere of course but I think the option would still be helpful to many people.

Best

**Comment by nielsdejong** [comment]
I think this will be helpful, but I'm also aware of the potentially big security issue here.
The app is currently designed to pick up the "environment variables" (those in config.json) at runtime. This also means that config.json is visible for everyone, example:
https://neodash.graphapp.io/config.json

Perhaps this can be a 'hidden feature' that is not visible by default, but appears in the developer documentation (with a ton of warnings). In other words, the standalonePassword/standaloneUsername passwords are not in `config.json`by default, but adding them will automatically fill in the credentials on user connect anyways. Thoughts?

This reminds me that I need to put some time into writing up a project wiki where all of these things are documented beyond the short description in the README. Will look into that one!

**Comment by dschmitz89** [comment]
Yes, that sounds like a good idea. If it is prominently documented in a wiki, developers should be aware of the risks. Auto filling is exactly what is needed. Experience tells me that as soon as "user login" appears somewhere in big corporations, controlling and data privacy departments unfortunately have to intervene even if they do not wish to themselves. Default read-only users help to circumvent such hassle. Thanks for your quick response!

**Comment by dschmitz89** [comment]
As of neodash 2.0.12, this functionality is implemented. Thank you! Closing the issue now.
