### ISSUE TITLE
Standalone mode can't find dashboard name in new browser

### ISSUE THREAD

**Issue by 0bserver07** [nielsdejong/neodash#89]
By the way, first of all, this project epic, thanks for open sourcing and happy to contribute at some point in near future!

Been playing around with deploying a standalone version, but I'm not able to have the Standalone load the dashboard that I have saved to the db.

The steps I have taken so far:

- make the dashboard locally
- save it to neo4j db. (saved as `"TEST0.1"`)
- change the name in the `config.json` file
```
   "standaloneDashboardName": "TEST0.1",
    "standaloneDashboardDatabase": "TEST0.1"
}
```
- run build
- After deploying, the neoDash still doesn't load the dashboard and goes into new or fresh view.

**Comment by nielsdejong** [comment]
hi @0bserver07 , great to hear!

To get this working in standalone mode you'll have to change `standaloneDashboardDatabase` to `neo4j` (or the name of the database you saved the dashboard in, if not the default)

E.g. this will be your config.json:
```
...
   "standaloneDashboardName": "TEST0.1",
   "standaloneDashboardDatabase": "neo4j"
...

I will expand more on this feature in the project wiki (currently a work in progress). Let me know if this works, looking forward to your contributions!

**Comment by 0bserver07** [comment]
Epic, worked like a charm!
Let me know if I can add notes to the readme as PR.
