### ISSUE TITLE
question : Is it possible to  pass the global parameter in the url?

### ISSUE THREAD

**Issue by jeffmsig** [nielsdejong/neodash#97]
Hello! Very useful app for me, it's great!
I hope to link my GIS app to Neodash Dashboard by clicking on an object to see is relationships.
Is there a way to do it?

Thanks.

**Comment by nielsdejong** [comment]
HI @jeffmsig ,

Great suggestion! Unfortunately not yet possible, but I think deep linking into NeoDash using an URL parameter is a great addition to the future. Will add it to the backlog.

Thank you,
Niels

**Comment by nielsdejong** [comment]
hi @jeffmsig - as of 2.0.14 this is now possible. As an example:
https://neodash.graphapp.io/?neodash_movie_title=The%20Matrix
This will set the dashboard parameter $neodash_movie_title to be used in your reports.

Good luck with your project,
Niels
